pool:
  vmImage: 'Ubuntu 16.04'

steps:
  - bash: |
      docker buildx create --use
      docker buildx build --platform linux/amd64,linux/arm64 -t eguee/consul-config-loader:travis .
    displayName: 'Install'

  - bash: docker images
    displayName: 'Run test'
